spring:
  application:
    name: ImprovedBillingSystem
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      key-prefix: "billing:"
      time-to-live: 10m

server:
  port: 8080

logging:
  level:
    root: info
    org:
      springframework:
        data:
          postgresql: debug
        web: debug
    com:
      jarviswuod:
        improvedbillingsystem: info
